### ISSUE TITLE
Decision tree for load balancing in Azure

### ISSUE THREAD

**Issue by mvark** [sastrykn/azserviceswhentouse#1]
Please add the [Decision tree for load balancing in Azure](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview) in your next update

**Comment by sastrykn** [comment]
hi @mvark , Thanks for the inputs and apologies for the delay. Have been very tied up and did not get time to visit this. Currently, updating the deck and will include your suggestions. Thanks again.

**Comment by sastrykn** [comment]
Included in my latest version. Thanks again
